#! /usr/bin/env bash

APP_NAME=app_datar
 
# have we done this?, then we should not do it again
if [ -n "$PRE_APP_PATH" ]; then
    echo "looks like we're already set... ignoring your request"
else
    # capture how things were before we started
    export PRE_APP_PATH=$PATH
    export PRE_APP_MANPATH=$MANPATH
    export PRE_APP_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
    export PRE_APP_PS1=$PS1

    HERE=`pwd`
    ROOT=${HERE}/build_output
    APP_ROOT=${HERE}
    LD_LIBRARY_PATH=${ROOT}/lib:$PRE_APP_LD_LIBRARY_PATH
    PATH=${HERE}/bin:${ROOT}/bin:$PATH
    PATH=${ROOT}/usr/local/ssl/bin/:$PATH
    PATH=${ROOT}/sbin:$PATH
    PATH=${ROOT}/usr/sbin:$PATH

    MANPATH=${ROOT}/usr/share/man/:$MANPATH
    PS1=\(${APP_NAME}\)$PS1

    function deactivate(){
        export PATH=$PRE_APP_PATH
        export PS1=$PRE_APP_PS1
        # try to leave the environment as it was, so if there was NO
        # LD_LIBRARY_PATH we leave it so that there isn't one
        if [ -n "$PRE_APP_LD_LIBRARY_PATH" ]; then
            export LD_LIBRARY_PATH=$PRE_APP_LD_LIBRARY_PATH
        else
            unset LD_LIBRARY_PATH
        fi
        if [ -n "$PRE_APP_MANPATH" ]; then
            export MANPATH=$PRE_APP_MANPATH
        else
            unset MANPATH
        fi
        unset PRE_APP_LD_LIBRARY_PATH
        unset PRE_APP_PATH
        unset PRE_APP_MANPATH
        unset PRE_APP_PS1
        unset -f deactivate
    }

    export PATH
    export LD_LIBRARY_PATH
    export PS1
    export MANPATH
    export APP_ROOT
    export -f deactivate
fi

